# Generated by Django 5.0.6 on 2024-09-12 15:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_adversisment_options_alter_article_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название компании', max_length=200)),
                ('description', models.TextField(help_text='Информация о компании')),
                ('video', models.FileField(blank=True, help_text='Видео компании', null=True, upload_to='company/videos/')),
                ('logo', models.ImageField(blank=True, help_text='Логотип компании', null=True, upload_to='company/logo/')),
                ('certificate', models.ImageField(blank=True, help_text='Сертификат компании', null=True, upload_to='company/certificates/')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'История', 'verbose_name_plural': 'Истории компании'},
        ),
        migrations.AlterField(
            model_name='history',
            name='description',
            field=models.TextField(help_text='Описание события'),
        ),
        migrations.AlterField(
            model_name='history',
            name='year',
            field=models.PositiveIntegerField(help_text='Год события (используйте формат YYYY)', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)]),
        ),
        migrations.AddField(
            model_name='history',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='store.company'),
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Электронная почта компании', max_length=254)),
                ('phone_number', models.CharField(help_text='Номер телефона компании', max_length=20)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='store.company')),
            ],
            options={
                'verbose_name': 'Реквизиты компании',
                'verbose_name_plural': 'Реквизиты компаний',
            },
        ),
    ]
