# Generated by Django 5.0.6 on 2024-09-13 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_client_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='photo',
        ),
    ]
