# Generated by Django 5.0.6 on 2024-09-12 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_company_alter_history_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'История', 'verbose_name_plural': 'Истории'},
        ),
        migrations.RemoveField(
            model_name='history',
            name='company',
        ),
        migrations.AlterField(
            model_name='history',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='year',
            field=models.PositiveIntegerField(help_text='Use the following format: YYYY', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)]),
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
