# Generated by Django 5.0.6 on 2024-09-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload client photo', null=True, upload_to='clients_photos/'),
        ),
    ]
