# Generated by Django 5.0.6 on 2024-09-12 16:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_history_options_remove_history_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'История', 'verbose_name_plural': 'Истории компании'},
        ),
        migrations.AddField(
            model_name='history',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='store.company'),
        ),
        migrations.AlterField(
            model_name='history',
            name='description',
            field=models.TextField(help_text='Описание события'),
        ),
        migrations.AlterField(
            model_name='history',
            name='year',
            field=models.PositiveIntegerField(help_text='Год события (используйте формат YYYY)', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
