# Generated by Django 5.0.6 on 2024-05-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.CharField(help_text='Enter book description', max_length=200),
        ),
    ]
