# Generated by Django 5.0.6 on 2024-09-12 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_history_options_history_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Электронная почта компании', max_length=254)),
                ('phone_number', models.CharField(help_text='Номер телефона компании', max_length=20)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='store.company')),
            ],
            options={
                'verbose_name': 'Реквизиты компании',
                'verbose_name_plural': 'Реквизиты компаний',
            },
        ),
    ]
